[project]
name = "guitar-ml-project-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jax[cuda12]>=0.7.0",
    "matplotlib>=3.10.5",
    "optax>=0.2.5",
]

[dependency-groups]
dev = [
    "ruff>=0.12.9",
]
